import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { Copy, Check, Plug, Save, ArrowUpRight, Loader2 } from 'lucide-react';
import { pluginRequest, type PluginSettings } from '../../lib/idGeneratorPlugin';
import { SIGNATURE_FONTS } from '../../lib/signature-options';
import { CITY_PRESETS } from '../../lib/employee-id-model';
import IdGeneratorStep from '../IdGeneratorStep';

const inputClass='w-full rounded-xl border border-white/15 bg-black/40 px-3 py-2 text-sm text-white focus:outline-none focus:border-cyan-200/60';
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm text-white/65"><span className="block mb-2">{label}</span>{children}</label>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="glass rounded-2xl border border-white/10 p-5 sm:p-6 space-y-4"><h2 className="text-lg text-white">{title}</h2>{children}</section>}
export default function IdGeneratorPlugin({panel=false}:{panel?:boolean}){
  const [data,setData]=useState<any>(null),[settings,setSettings]=useState<PluginSettings|null>(null),[etag,setEtag]=useState('');
  const [message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[secret,setSecret]=useState(''),[copied,setCopied]=useState('');
  const load=async()=>{const r=await pluginRequest('settings');setData(r.body);setSettings(r.body.settings);setEtag(r.etag);};
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const change=(section:'employee'|'signature'|'photo',key:string,value:any)=>setSettings(s=>s?{...s,[section]:{...s[section],[key]:value}}:s);
  const copy=async(kind:string,value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(kind);setTimeout(()=>setCopied(''),2500);}catch{setError('Clipboard was blocked. Select and copy the displayed text.');}};
  const save=async()=>{setBusy(true);setError('');setMessage('');try{const r=await pluginRequest('settings',{method:'PUT',headers:{'Content-Type':'application/json','If-Match':etag},body:JSON.stringify(settings)});setEtag(r.etag);setSettings(r.body.settings);setMessage('Settings saved on this PC.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const pair=async()=>{setBusy(true);setError('');try{await pluginRequest('pair',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret})});setSecret('');await load();setMessage('Ports key saved securely for this Windows user.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(!settings)return <div className="glass rounded-2xl p-6 text-white/65">{error||'Loading ID Generator…'}</div>;
  const h=data.health,ready=h?.worker?.online&&h?.template?.present&&(h?.photoshop?.found||h?.dryRun);
  if(panel)return <div className="space-y-5"><div className="glass rounded-2xl p-4 flex flex-wrap items-center justify-between gap-3 text-sm text-white/70"><span className="flex items-center gap-2"><span className={`w-2 h-2 rounded-full ${ready?'bg-emerald-300':'bg-amber-300'}`}/>{ready?'Connected to Studio':'Start Studio to generate'} · {data.configured?'Ports key configured':'Ports pairing needed'}</span><Link to="/settings/id-generator" className="flex gap-2 items-center text-cyan-100">Plugin settings <ArrowUpRight size={14}/></Link></div><IdGeneratorStep initialPluginSettings={settings} onBack={()=>location.assign('/settings/id-generator')}/></div>;
  return <div className="max-w-4xl mx-auto space-y-5 text-white">
    <div className="flex items-center justify-between gap-4"><div><div className="text-cyan-100/60 text-xs tracking-widest uppercase mb-2">Cyclone Ports · PC plugin</div><h1 className="text-3xl">ID Generator</h1><p className="text-white/55 text-sm mt-2">Your employee generator, with saved defaults for Glass and phone runs.</p></div><Plug className="text-cyan-100/60 shrink-0" size={30}/></div>
    <Card title="Connection"><div className="flex flex-wrap gap-2"><span className="px-3 py-1 rounded-full bg-white/5 text-sm">{ready?'Studio online':'Worker or template needs attention'}</span><span className="px-3 py-1 rounded-full bg-white/5 text-sm">{data.configured?'Ports key configured':'Awaiting Ports key'}</span></div>
      <div className="flex flex-wrap items-center gap-3"><Link to="/plugins/id-generator" className="rounded-full bg-white text-black px-4 py-2 text-sm">Open generator</Link><button onClick={()=>copy('manifest',data.manifest.endpoint+'/cyclone-plugin.json')} className="flex items-center gap-2 rounded-full border border-white/20 px-4 py-2 text-sm">{copied==='manifest'?<Check size={14}/>:<Copy size={14}/>} {copied==='manifest'?'Manifest URL copied':'Copy manifest URL'}</button><button onClick={()=>load().catch(e=>setError(e.message))} className="text-sm text-white/60">Refresh health</button></div>
      <code className="block text-xs text-cyan-100/70 break-all">{data.manifest.endpoint}/cyclone-plugin.json</code>
      <p className="text-white/50 text-sm">Add this manifest in Glass Ports and allow the photo, generation and result ports. Paste the plugin key Glass supplies below.</p>
      <p className="text-white/50 text-sm">Photo and signature preparation runs locally. Exports also require Photoshop to be openable, with no blocking sign-in or subscription screen.</p>
      <div className="flex gap-2"><input aria-label="Ports plugin key" type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Plugin key from Glass" className={inputClass}/><button disabled={busy||secret.length<16} onClick={pair} className="border border-white/20 rounded-xl px-4 text-sm disabled:opacity-40">Connect</button></div>
      <label className="flex gap-2 text-sm text-white/70"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Accept jobs from Ports</label>
    </Card>
    <Card title="Employee defaults"><div className="grid sm:grid-cols-2 gap-4">
      <Field label="Company"><input className={inputClass} value={settings.employee.company_name} onChange={e=>change('employee','company_name',e.target.value)}/></Field>
      <Field label="Department"><input className={inputClass} value={settings.employee.department} onChange={e=>change('employee','department',e.target.value)}/></Field>
      <Field label="Number format"><select className={inputClass} value={settings.employee.country} onChange={e=>change('employee','country',e.target.value)}><option value="NL">Netherlands</option><option value="DE">Germany</option><option value="OTHER">Other / company format</option></select></Field>
      <Field label="MRZ layout"><select className={inputClass} value={settings.employee.doc_type} onChange={e=>change('employee','doc_type',e.target.value)}><option value="id_card">Card · TD1</option><option value="passport">Booklet · TD3</option></select></Field>
      <Field label="City · choose or type your own"><input list="plugin-cities" className={inputClass} value={settings.employee.city_of_birth} onChange={e=>{change('employee','city_of_birth',e.target.value);change('employee','company_location',e.target.value);}}/><datalist id="plugin-cities">{CITY_PRESETS.map(city=><option key={city} value={city}/>)}</datalist></Field>
      <Field label="Company location"><input className={inputClass} value={settings.employee.company_location} onChange={e=>change('employee','company_location',e.target.value)}/></Field>
      <Field label={`Height · ${settings.employee.height}`}><input type="range" min={140} max={210} value={Math.round(Number(settings.employee.height.replace(',','.').replace(' m',''))*100)} onChange={e=>change('employee','height',`${Math.floor(Number(e.target.value)/100)},${String(Number(e.target.value)%100).padStart(2,'0')} m`)} className="w-full accent-cyan-100"/></Field>
      <Field label="Output"><select className={inputClass} value={settings.employee.export_format} onChange={e=>change('employee','export_format',e.target.value)}>{['png','pdf','psd'].map(v=><option key={v}>{v}</option>)}</select></Field>
    </div><p className="text-sm text-white/50">Document and personal numbers can be supplied per employee. Empty values use the current generator's format and validation rules.</p><label className="flex gap-2 text-sm text-white/70"><input type="checkbox" checked={settings.employee.generate_mockups} onChange={e=>change('employee','generate_mockups',e.target.checked)}/>Generate existing mockups</label></Card>
    <Card title="Signature"><div className="grid sm:grid-cols-2 gap-4"><Field label="Style"><select className={inputClass} value={settings.signature.font} onChange={e=>change('signature','font',e.target.value)}>{SIGNATURE_FONTS.slice(0,9).map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></Field><Field label="Signature text"><select className={inputClass} value={settings.signature.name_mode} onChange={e=>change('signature','name_mode',e.target.value)}><option value="first_name_only">Employee first name</option><option value="full_name">Employee full name</option><option value="custom">Custom text</option></select></Field>{settings.signature.name_mode==='custom'&&<Field label="Custom signature"><input maxLength={40} className={inputClass} value={settings.signature.text} onChange={e=>change('signature','text',e.target.value)}/></Field>}<Field label={`Size · ${settings.signature.scale.toFixed(2)}×`}><input className="w-full accent-cyan-100" type="range" min={0.5} max={3} step={0.01} value={settings.signature.scale} onChange={e=>change('signature','scale',Number(e.target.value))}/></Field></div><p className="text-sm text-white/50">Paul Signature is the default. Every generated signature is a transparent 420 × 123 PNG, using the Studio's existing raster code.</p></Card>
    <Card title="Employee photo"><label className="flex gap-2 text-sm text-white/70"><input type="checkbox" checked={settings.photo.remove_background} onChange={e=>change('photo','remove_background',e.target.checked)}/>Remove background locally</label><div className="grid sm:grid-cols-3 gap-4">{(['zoom','x','y'] as const).map(k=><Field key={k} label={k==='zoom'?`Crop zoom · ${settings.photo[k].toFixed(2)}×`:k==='x'?'Horizontal crop':'Vertical crop'}><input type="range" min={k==='zoom'?1:0} max={k==='zoom'?5:1} step={0.01} value={settings.photo[k]} onChange={e=>change('photo',k,Number(e.target.value))} className="w-full accent-cyan-100"/></Field>)}</div><p className="text-sm text-white/50">Exports at 2421 × 3292. Open the generator to position an individual photo with the existing crop editor.</p></Card>
    <Card title="Local retention"><Field label="Delete plugin employee files after"><select className={inputClass} value={settings.retention_hours} onChange={e=>setSettings({...settings,retention_hours:Number(e.target.value)})}>{[1,24,48,72,168].map(h=><option key={h} value={h}>{h} hours</option>)}</select></Field><p className="text-sm text-white/50">Applies to incoming plugin photos and completed plugin jobs. Active jobs are kept until they finish. Ordinary Studio jobs keep their existing storage behavior.</p></Card>
    <div aria-live="polite">{error&&<p className="text-rose-200 text-sm">{error}</p>}{message&&<p className="text-emerald-200 text-sm">{message}</p>}</div><button disabled={busy} onClick={save} className="flex items-center gap-2 rounded-full bg-white text-black px-6 py-3 text-sm disabled:opacity-40">{busy?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Save settings</button>
    <details className="glass rounded-2xl p-5 text-sm"><summary className="cursor-pointer text-white/70">For agents and developers</summary><p className="text-white/50 mt-3">Send the photo with file.out, then x.id-generator.generate. Match result waits by requestId; select front, back, full, pdf, psd or an available mockup.</p><div className="flex gap-3 mt-3"><button className="text-cyan-100" onClick={async()=>{try{const r=await pluginRequest('schema');await copy('schema',JSON.stringify(r.body,null,2));}catch(e){setError((e as Error).message);}}}>{copied==='schema'?'Schema copied':'Copy agent schema'}</button><a href={data.manifest.schemaUrl} target="_blank" rel="noreferrer" className="text-white/60">Open schema</a></div><pre className="overflow-auto text-xs text-white/45 mt-4">{JSON.stringify(data.manifest,null,2)}</pre></details>
  </div>;
}
